version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing global tools if not already present"
      - npm install -g npm@9 || echo "npm already installed"
      - npm install -g serverless@3 || echo "serverless v3 already installed"
      - echo "Installing required build tools"
      - yum install -y gcc gcc-c++ make python3
      - echo "Installing frontend dependencies"
      - cd frontend
      - if [ ! -d "node_modules" ]; then npm install --legacy-peer-deps; fi
      - echo "Finished installing frontend dependencies"

  build:
    commands:
      - echo "Deploying backend API"
      - cd ../backend
      - serverless deploy
      - echo "Finished deploying backend API"

cache:
  paths:
    - "frontend/node_modules/**/*"
