version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Fixing npm version for Node 18
      - npm install -g npm@9
      - echo Installing serverless
      - npm install -g serverless
      - echo Installing required build tools
      - yum install -y gcc gcc-c++ make python3
      - echo Installing todo API dependencies
      - cd backend
      - rm -rf node_modules package-lock.json
      - npm install --legacy-peer-deps
      - echo Finished installing todo API dependencies
  build:
    commands:
      - echo Deploying todo API
      - serverless deploy
      - echo Finished deploying todo API

cache:
  paths:
    - "backend/node_modules/**/*"


